### ISSUE TITLE
Android Studio 1.2 not displaying the code styles

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [square/java-code-styles#10]
Hello. I was using this code style in Android Studio 1.1 without any trouble. I updated to the canary 1.2 version and i am trying to set the code style again, but it does not appear when i try to "manage" code styles. What's the matter with it? Might the ~/AndroidStudio/config/codestyles folder have changed its path or name ? I runned the installation script again, but still happening.

Thanks in advance.

**Comment by JakeWharton** [comment]
Both the migration from old AS and a fresh install and the script worked for me.

You can copy the `SquareAndroid.xml` into `~/Library/Preferences/AndroidStudioPreview1.2/codestyles/SquareAndroid.xml` or `~/.AndroidStudioPreview1.2/codestyles/SquareAndroid.xml` manually depending on your OS.

Unless this becomes a problem for a lot of people, I don't think there's any action to take here. I think your upgrade just got botched unfortunately.

**Comment by JorgeCastilloPrz** [comment]
Yes, you are right. I didnt know that previews have a different config folder. It is working propperly now. Thanks form your help.
