### ISSUE TITLE
SquareAndroid code style doesn't define arrangement for XML 

### ISSUE THREAD

**Issue by ravikumar-n** [square/java-code-styles#21]
The "SquareAndroid" code style doesn't have any XML arrangement predefined. (Editor > Code Style > XML > (Scheme:SquareAndroid) Arrangement )

I'm setting it by using "Set From > Predefined style > Android" to enforce XML tags arrangement.

Is this an intended behavior? If not can I make a PR?

**Comment by JakeWharton** [comment]
> can I make a PR

feel free! In general, id="" first, then layout_*, then everything else, then style="".

**Comment by ravikumar-n** [comment]
@JakeWharton Namespace declarations comes before id ?, style comes before tools?

Below is a sample xml formatted using standard Android template:
```
<android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:id="@+id/toolbar"
  style="@style/AppTheme"
  android:layout_width="match_parent"
  android:layout_height="?actionBarSize"
  android:alpha="0.9f"
  android:background="?attr/colorPrimary"
  android:theme="@style/ActionBarThemeOverlay"
  app:contentInsetStart="?actionBarInsetStart"
  app:layout_scrollFlags="scroll|enterAlways"
  app:popupTheme="@style/ActionBarPopupThemeOverlay"
  app:titleTextAppearance="@style/ActionBar.TitleText"
  tools:actionBarNavMode="standard"
  tools:context=".ui.activities.DashboardActivity" />
```
Could you convert this sample to SquareAndroid style? (Based on this I will create the formatter.)

**Comment by JakeWharton** [comment]
```xml
<android.support.v7.widget.Toolbar
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?actionBarSize"
    android:alpha="0.9f"
    android:background="?attr/colorPrimary"
    android:theme="@style/ActionBarThemeOverlay"
    app:contentInsetStart="?actionBarInsetStart"
    app:layout_scrollFlags="scroll|enterAlways"
    app:popupTheme="@style/ActionBarPopupThemeOverlay"
    app:titleTextAppearance="@style/ActionBar.TitleText"
    tools:actionBarNavMode="standard"
    tools:context=".ui.activities.DashboardActivity"
    style="@style/AppTheme"
    />
```

**Comment by johnjohndoe** [comment]
For your consideration: I prefer to put `style` before individual settings such as `android:alpha="0.9f"` which might be used to **overwrite** what is defined in `style`.

**Comment by JakeWharton** [comment]
We put it after because the local attributes are of higher precedence (i.e., more important)

**Comment by johnjohndoe** [comment]
Sounds like we mean the same in the end only that I call it the "overwrite" perspective. It would be interesting in which order the attributes are parsed.
