### ISSUE TITLE
Kotlin code styles

### ISSUE THREAD

**Issue by heinrichreimer** [square/java-code-styles#41]
Most things should already be in the style guide.
But we should double check and discuss Kotlins [official style guide](http://kotlinlang.org/docs/reference/coding-conventions.html).

**Comment by JakeWharton** [comment]
We already include Kotlin styles. What are you asking for here specifically?

**Comment by heinrichreimer** [comment]
Nothing in particular, I only wanted to check if all all rules from the Kotlin documentation are covered.
I'm not experienced with IDEA code style templates at all to be honest, but if https://github.com/square/java-code-styles already covers these rules it should probably be included in the README.md.

**Comment by JakeWharton** [comment]
We don't strictly adhere to their rules and are not committing to it in the
future. We won't be using 4 spaces, for example, unless someone convinces
us to switch to 4 spaces for every language which seems extremely unlikely.

**Comment by heinrichreimer** [comment]
Kotlin specific styles to be considered:
- Spacing
  - Around [colons](http://kotlinlang.org/docs/reference/coding-conventions.html#colon)
  - Around [curly braces](http://kotlinlang.org/docs/reference/coding-conventions.html#lambdas) in lambda expressions
- Omit return type in [`Unit` returns](http://kotlinlang.org/docs/reference/coding-conventions.html#unit)
- Recommend [string interpolation](http://kotlinlang.org/docs/reference/idioms.html#string-interpolation) over string concatenation

**Comment by JakeWharton** [comment]
Spacing should be covered by the default Kotlin values. The other two
aren't syntax styles and thus are out of scope of this project.

**Comment by heinrichreimer** [comment]
Thank you very much @JakeWharton! 👍
