### ISSUE TITLE
Error while installing on ubuntu

### ISSUE THREAD

**Issue by saisurya-k** [square/java-code-styles#57]
Getting this error while installing on Ubuntu 17.10
```
install.sh: 6: install.sh: Bad substitution
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
install.sh: 15: install.sh: [[: not found
```
install.sh has this code on line 15
` if [[ -d $i ]]; then`

**Comment by saisurya-k** [comment]
After changing the **[[ -d $i ]]** to **[-d $i ]** it worked.

**Comment by vivekkartha** [comment]
I had the same issue as well, and the mentioned fix fixed it

**Comment by rcfgnu** [comment]
Or you can use `./install.sh` instead of `sh install sh` without replacing anything.
