### ISSUE TITLE
SquareAndroid: Kotlin method declaration params should only wrap if long

### ISSUE THREAD

**Issue by edenman** [square/java-code-styles#58]
```
  private fun createTemporaryCoverageFiles(serialId1: String, serialId2: String) {
```
The current code style forces that to 
```
  private fun createTemporaryCoverageFiles(
    serialId1: String,
    serialId2: String
  ) {
```
Which seems wrong to me.  It also does some aggressive line-wraps around long method calls that I think is wrong:
```
            assertThat(cliArgs).isEqualTo(
                "this assertion shouldn't be executed, exception is expected")
```
turns into 
```
            assertThat(cliArgs).isEqualTo(
                "this assertion shouldn't be executed, exception is expected"
            )
```
Are these intentional?  Want me to submit a PR to fix?

**Comment by oldergod** [comment]
For what it's worth, I like how the style guide manages the two behaviours you mentioned. I don't like it forces a line-wrap from the second `.` of a chain though, like:
```kotlin
thing.foo()
  .bar()
```

**Comment by edenman** [comment]
I have since realized there are a ton of things I don't like about SquareAndroid for Kotlin, so I'm just gonna fork

**Comment by swankjesse** [comment]
Wanna list em? If our style is objectively bad I would like to be self-aware!

**Comment by edenman** [comment]
I don't think it's objectively bad, it just looks wrong to my eyes.  In addition to the ones above:

1. I turned off the `New line after '('` and `Place ')' on new line` settings across the board.  
2. Went to `Wrap if long` for everything that was set to `Always wrap` (in particular, small data classes that fit on one line read just fine to me)

It looks like you guys are in line with the [Kotlin standards](https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting), so don't mind me.

**Comment by swankjesse** [comment]
SGTM. I wanna eventually get tools to do everything except for explicit newlines which I don’t think the tools will ever do particularly well.
