### ISSUE TITLE
Import does not work with Intellij Idea CE 2020.1

### ISSUE THREAD

**Issue by jmprathab** [square/java-code-styles#71]
* Tried to import the styles into Intellij Idea CE 2020.1
* But import does not seem to take effect.
* Looks like Intellij configuration directory has been changed as per (https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html?_ga=2.19808703.666856556.1587275963-1788437375.1573216295#default-dirs)

**Comment by JakeWharton** [comment]
Fixed by #72!
